"""Meta-intelligence — insights about the quality and reliability of the intelligence itself.

Self-reflexive analysis:
- Representation quality assessment (is the model good enough?)
- Insight reliability scoring (which insights to trust?)
- Corpus completeness diagnosis (is the corpus sufficient?)
- Model capacity assessment (is the model big enough?)
"""

import logging

from tcd_jepa.manifold.insight_engine import Insight
from tcd_jepa.manifold.lineage import make_lineage_id

logger = logging.getLogger("tcd_jepa.meta_intelligence")


class MetaIntelligenceEngine:
    """Generates meta-insights about the quality and reliability of the analysis."""

    def generate(self, all_insights: list[Insight], profile, kpis: dict) -> list[Insight]:
        """Generate meta-intelligence insights.

        Args:
            all_insights: All insights generated by other engines.
            profile: DeepSignalProfile.
            kpis: Computed KPIs from evaluation.
        """
        insights = []
        try:
            insights.extend(self._representation_quality_insights(profile, kpis))
            insights.extend(self._insight_reliability_assessment(all_insights, profile))
            insights.extend(self._corpus_completeness_insights(profile, kpis))
            insights.extend(self._model_capacity_insights(profile, kpis))
        except Exception as e:
            logger.warning(f"Meta insight generation failed: {e}")
        return insights

    def _representation_quality_insights(self, profile, kpis: dict) -> list[Insight]:
        """Assess quality of learned representations."""
        insights = []

        effective_rank = profile.effective_rank
        uniformity = profile.uniformity
        neighborhood = profile.neighborhood_preservation
        link_auc = profile.link_prediction_auc

        # Build quality assessment
        quality_scores = []
        details = []

        if effective_rank > 0:
            details.append(f"Effective rank: {effective_rank:.1f}")
            # Higher effective rank = better use of dimensions
            quality_scores.append(min(1.0, effective_rank / 50))

        if uniformity != 0:
            details.append(f"Uniformity: {uniformity:.3f}")
            # Uniformity closer to 0 = better (less clustered in hypersphere)
            quality_scores.append(min(1.0, max(0, 1.0 + uniformity / 5)))

        if neighborhood > 0:
            details.append(f"Neighborhood preservation: {neighborhood:.3f}")
            quality_scores.append(neighborhood)

        if link_auc > 0:
            details.append(f"Link prediction AUC: {link_auc:.3f}")
            quality_scores.append(link_auc)

        if not quality_scores:
            return insights

        overall_quality = sum(quality_scores) / len(quality_scores)
        quality_label = (
            "excellent" if overall_quality > 0.8 else
            "good" if overall_quality > 0.6 else
            "moderate" if overall_quality > 0.4 else
            "poor"
        )

        # Recommendations
        recommendations = []
        if effective_rank > 0 and effective_rank < 20:
            recommendations.append("Low effective rank suggests the model has underutilized capacity — consider longer training or more data.")
        if uniformity < -3:
            recommendations.append("High uniformity indicates representations are too clustered — consider increasing embedding dimension.")
        if neighborhood > 0 and neighborhood < 0.5:
            recommendations.append("Low neighborhood preservation — the model isn't preserving local manifold structure well.")
        if link_auc > 0 and link_auc < 0.6:
            recommendations.append("Low link prediction AUC — causal structure isn't well-captured in embeddings.")

        insights.append(Insight(
            category="model_quality",
            severity="low" if overall_quality > 0.6 else "medium",
            title=f"Representation quality: {quality_label} ({overall_quality:.0%})",
            description=(
                f"Overall representation quality: {quality_label} ({overall_quality:.0%}). "
                f"{'. '.join(details)}. "
                f"{' '.join(recommendations) if recommendations else 'No issues detected.'}"
            ),
            evidence=[],
            entities=[],
            confidence=0.85,
            insight_id=make_lineage_id("insight"),
            derivation_steps=["representation_metrics", "quality_scoring", "meta_assessment"],
        ))

        return insights

    def _insight_reliability_assessment(self, all_insights: list[Insight], profile) -> list[Insight]:
        """Assess which insights are most/least reliable."""
        insights = []

        if len(all_insights) < 3:
            return insights

        # Categorize insights by reliability
        high_confidence = [i for i in all_insights if i.confidence > 0.75 and i.sensitivity > 0.5]
        _low_confidence = [i for i in all_insights if i.confidence < 0.5]
        with_contradictions = [i for i in all_insights if i.contradicts]
        with_sensitivity = [i for i in all_insights if i.sensitivity > 0]

        # Consensus insights: high confidence, no contradictions, stable
        consensus = [
            i for i in all_insights
            if i.confidence > 0.7 and not i.contradicts and i.sensitivity >= 0.5
        ]

        total = len(all_insights)
        consensus_pct = len(consensus) / total if total > 0 else 0

        insights.append(Insight(
            category="insight_reliability",
            severity="low" if consensus_pct > 0.5 else "medium",
            title=f"Insight reliability: {len(consensus)}/{total} are high-confidence consensus",
            description=(
                f"Of {total} insights generated, {len(high_confidence)} have high confidence "
                f"(>75%). {len(with_contradictions)} have contradictions. "
                f"{len(with_sensitivity)} have sensitivity scores. "
                f"{len(consensus)} insights ({consensus_pct:.0%}) are consensus findings "
                f"(high confidence, no contradictions, stable under perturbation). "
                f"{'These consensus insights should be treated as reliable findings.' if consensus else 'Consider additional data to strengthen insight reliability.'}"
            ),
            evidence=[],
            entities=[],
            confidence=0.8,
            insight_id=make_lineage_id("insight"),
            derivation_steps=["insight_collection", "confidence_aggregation", "reliability_assessment"],
        ))

        return insights

    def _corpus_completeness_insights(self, profile, kpis: dict) -> list[Insight]:
        """Diagnose whether the corpus is sufficient."""
        insights = []

        coverage = profile.coverage_ratio
        _num_modules = profile.num_modules
        betti = profile.betti_numbers

        recommendations = []

        # Coverage-based diagnosis
        if coverage < 0.5:
            recommendations.append(
                f"Only {coverage:.0%} of the corpus is well-modeled. "
                f"Consider adding more documents to fill knowledge gaps."
            )
        elif coverage < 0.8:
            recommendations.append(
                f"{coverage:.0%} coverage is moderate. Some blind spots remain."
            )

        # Topology-based diagnosis
        h2_voids = betti.get(2, 0)
        if h2_voids > 0:
            recommendations.append(
                f"{h2_voids} topological voids (H2) detected — "
                f"these indicate missing bridging documents between topic clusters."
            )

        # Convergence-based diagnosis
        if profile.representation_stability > 0.8:
            recommendations.append("High representation stability — the model has learned the corpus well.")
        elif profile.representation_stability < 0.3:
            recommendations.append(
                "Low representation stability — the model may need more training epochs "
                "or the corpus may be too complex for the current model size."
            )

        if not recommendations:
            return insights

        # Overall quality
        completeness = min(1.0, coverage * 0.5 + profile.representation_stability * 0.3 + (0.2 if h2_voids == 0 else 0))

        insights.append(Insight(
            category="corpus_diagnosis",
            severity="medium" if completeness < 0.6 else "low",
            title=f"Corpus completeness: {completeness:.0%}",
            description=(
                f"Corpus diagnosis — completeness: {completeness:.0%}. "
                f"{' '.join(recommendations)} "
                f"Neighborhood preservation: {profile.neighborhood_preservation:.3f}. "
                f"Link prediction AUC: {profile.link_prediction_auc:.3f}."
            ),
            evidence=[],
            entities=[],
            confidence=0.7,
            insight_id=make_lineage_id("insight"),
            derivation_steps=["coverage_analysis", "topology_diagnosis", "convergence_assessment", "corpus_diagnosis"],
        ))

        return insights

    def _model_capacity_insights(self, profile, kpis: dict) -> list[Insight]:
        """Assess whether the model has sufficient capacity."""
        insights = []

        effective_rank = profile.effective_rank
        if effective_rank == 0:
            return insights

        # Capacity utilization
        num_modules = profile.num_modules
        module_types = profile.module_types

        details = [f"Crystallized modules: {num_modules}"]
        if module_types:
            type_strs = [f"{v} {k}s" for k, v in module_types.items()]
            details.append(f"Types: {', '.join(type_strs)}")

        # Module performance spread
        if profile.module_performance:
            losses = list(profile.module_performance.values())
            if losses:
                avg_loss = sum(losses) / len(losses)
                details.append(f"Average module loss: {avg_loss:.4f}")

        convergence_state = "converged" if profile.representation_stability > 0.8 else "still learning"
        details.append(f"State: {convergence_state}")

        insights.append(Insight(
            category="model_quality",
            severity="low",
            title=f"Model capacity: {num_modules} modules, effective rank {effective_rank:.1f}",
            description=(
                f"Model capacity assessment. {'. '.join(details)}. "
                f"Coverage: {profile.coverage_ratio:.0%}. "
                f"{'The model has learned stable representations.' if profile.representation_stability > 0.7 else 'Consider additional training to stabilize representations.'}"
            ),
            evidence=[],
            entities=[],
            confidence=0.75,
            insight_id=make_lineage_id("insight"),
            derivation_steps=["module_analysis", "capacity_assessment", "convergence_evaluation"],
        ))

        return insights
